services:
  ros:
    image: osrf/ros:noetic-desktop-full
    container_name: ros_noetic
    network_mode: host
    privileged: true

    volumes:
      - ../ros_ws:/drone_project
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost

    stdin_open: true
    tty: true
    working_dir: /drone_project
    command: bash
